[TestCase("text", new[] { "text" })]
[TestCase("hello world", new[] { "hello", "world" })]
[TestCase("'x y'", new[] { "x y" })]
[TestCase("'x ", new[] { "x " })]
[TestCase(@"""a 'b' 'c' d""", new[] { "a 'b' 'c' d" })]
[TestCase(@"a""b c d e""", new[] { "a", "b c d e" })]
[TestCase(@"""b c d e""f", new[] { "b c d e", "f" })]
[TestCase(@"""a \""c\""""", new[] { @"a ""c""" })]
[TestCase(@"""\\""", new[] { "\\" })]
[TestCase(@" '' ", new[] { "" })]
[TestCase(@"'a\'a\'a'", new[] { "a'a'a" })]
[TestCase(@"'""1""", new[] { @"""1""" })]
[TestCase(" 1 ", new[] { "1" })]
[TestCase("", new string[] { })]
[TestCase("    ", new string[] { })]
[TestCase("   multiple     spaces   ", new string[] { "multiple", "spaces" })]
[TestCase("   oneField   ", new string[] { "oneField" })]
[TestCase("   a     b   c   ", new string[] { "a", "b", "c" })]
public static void RunTests(string input, string[] expectedOutput) => Test(input, expectedOutput);